@token=12345

### Create Function
POST http://localhost:4000/function
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "creator_id":1,
    "name":"My Function",
    "language":"js",
    "timeout":60
}

### Get Function
GET  http://localhost:4000/function
Authorization: Bearer {{token}}

### Delete Function
DELETE http://localhost:4000/function?id=1
Authorization: Bearer {{token}}


### Run Function
GET http://localhost:4000/function/run/30
Content-Type: application/json

{
    "operation":"div",
    "a":6,
    "b":3
}