// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createFunctionStmt, err = db.PrepareContext(ctx, createFunction); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFunction: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteFunctionsByIdAndCreatorIdStmt, err = db.PrepareContext(ctx, deleteFunctionsByIdAndCreatorId); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFunctionsByIdAndCreatorId: %w", err)
	}
	if q.getFunctionsByCreatorIdStmt, err = db.PrepareContext(ctx, getFunctionsByCreatorId); err != nil {
		return nil, fmt.Errorf("error preparing query GetFunctionsByCreatorId: %w", err)
	}
	if q.getFunctionsByIdStmt, err = db.PrepareContext(ctx, getFunctionsById); err != nil {
		return nil, fmt.Errorf("error preparing query GetFunctionsById: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createFunctionStmt != nil {
		if cerr := q.createFunctionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFunctionStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteFunctionsByIdAndCreatorIdStmt != nil {
		if cerr := q.deleteFunctionsByIdAndCreatorIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFunctionsByIdAndCreatorIdStmt: %w", cerr)
		}
	}
	if q.getFunctionsByCreatorIdStmt != nil {
		if cerr := q.getFunctionsByCreatorIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFunctionsByCreatorIdStmt: %w", cerr)
		}
	}
	if q.getFunctionsByIdStmt != nil {
		if cerr := q.getFunctionsByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFunctionsByIdStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	createFunctionStmt                  *sql.Stmt
	createUserStmt                      *sql.Stmt
	deleteFunctionsByIdAndCreatorIdStmt *sql.Stmt
	getFunctionsByCreatorIdStmt         *sql.Stmt
	getFunctionsByIdStmt                *sql.Stmt
	getUserStmt                         *sql.Stmt
	getUserByEmailStmt                  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		createFunctionStmt:                  q.createFunctionStmt,
		createUserStmt:                      q.createUserStmt,
		deleteFunctionsByIdAndCreatorIdStmt: q.deleteFunctionsByIdAndCreatorIdStmt,
		getFunctionsByCreatorIdStmt:         q.getFunctionsByCreatorIdStmt,
		getFunctionsByIdStmt:                q.getFunctionsByIdStmt,
		getUserStmt:                         q.getUserStmt,
		getUserByEmailStmt:                  q.getUserByEmailStmt,
	}
}
