// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	UserID    int64          `json:"user_id"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Type      string         `json:"type"`
	CreatedAt time.Time      `json:"created_at"`
	SubjectID sql.NullString `json:"subject_id"`
}
