// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Function struct {
	ID        int64          `json:"id"`
	CreatorID int64          `json:"creator_id"`
	Name      sql.NullString `json:"name"`
	Language  string         `json:"language"`
	Timeout   int64          `json:"timeout"`
	FileRef   string         `json:"file_ref"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	UserID    int64     `json:"user_id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}
