// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Function struct {
	ID         int64     `json:"id"`
	CreatorID  int64     `json:"creator_id"`
	Name       string    `json:"name"`
	Language   string    `json:"language"`
	Timeout    int64     `json:"timeout"`
	OutputType string    `json:"output_type"`
	CreatedAt  time.Time `json:"created_at"`
}

type FunctionCall struct {
	ID         int64     `json:"id"`
	FunctionID int64     `json:"function_id"`
	Output     string    `json:"output"`
	Stdout     string    `json:"stdout"`
	Error      string    `json:"error"`
	Cost       int64     `json:"cost"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	UserID    int64     `json:"user_id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}
