// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateFunction(ctx context.Context, arg CreateFunctionParams) (*Function, error)
	GetHealth(ctx context.Context) (interface{}, error)
	GetUser(ctx context.Context) (*User, error)
}

var _ Querier = (*Queries)(nil)
