// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateFunction(ctx context.Context, arg CreateFunctionParams) (*Function, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteFunctionsByIdAndCreatorId(ctx context.Context, arg DeleteFunctionsByIdAndCreatorIdParams) error
	GetFunctionsByCreatorId(ctx context.Context, creatorID int64) ([]*Function, error)
	GetFunctionsById(ctx context.Context, id int64) (*Function, error)
	GetUser(ctx context.Context) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
}

var _ Querier = (*Queries)(nil)
