// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT user_id, email, password, type, created_at
FROM users
`

func (q *Queries) GetUser(ctx context.Context) (*User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Password,
		&i.Type,
		&i.CreatedAt,
	)
	return &i, err
}
